### ISSUE TITLE
No package '/root/devnet/extern/filecoin-ffi/generated/../filcrypto.pc' found  

### ISSUE THREAD

**Issue by morrigan** [textileio/lotus-devnet#33]
When trying to run with `go run main.go`

![Screenshot 2020-10-19 at 15 43 14](https://user-images.githubusercontent.com/4976604/96458954-d1eb1f80-1221-11eb-82dc-437f37138fda.png)

**Comment by jsign** [comment]
You need to do `make` before that, since it has external dependencies.

**Comment by jsign** [comment]
Refer soon to the readme where I'll add better steps.
