### ISSUE TITLE
`lastest` tag on dockerhub points to `v1.1.3` instead of one of the more recent builds

### ISSUE THREAD

**Issue by mikeseese** [textileio/lotus-devnet#41]
Just as a heads up, your README points to use the `latest` tag of the docker image, but `latest` points to an old build (v1.1.3): https://hub.docker.com/r/textile/lotus-devnet/tags

**Comment by jsign** [comment]
Thanks, I'll fix that in the next release.

**Comment by jsign** [comment]
Fixed now that v1.4.1 got released, thanks again!
